### ISSUE TITLE
Install issues: 

### ISSUE THREAD

**Issue by msimonc** [chromakode/react-html-email#13]
Thanks for this project,

Using:
    React 15.0.2, Webpack, Babel 6.8.0,

When I run:
import ReactHTMLEmail from 'react-html-email'
ReactHTMLEmail.injectReactEmailAttributes();

I get:
client:47 ./~/react-html-email/lib/supportMatrix.json
Module parse failed: /Projects/SMS/sms-app-factory/af-secure/node_modules/react-html-email/lib/supportMatrix.json Unexpected token (1:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:12)
    at Parser.pp.raise (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.semicolon (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1976:8)
    at Parser.pp.parseStatement (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1754:188)
    at Parser.pp.parseBlock (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1991:21)
    at Parser.pp.parseStatement (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1735:19)
    at Parser.pp.parseTopLevel (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/Projects/SMS/sms-app-factory/af-secure/node_modules/acorn/dist/acorn.js:882:44)
 @ ./~/react-html-email/lib/StyleValidator.js 13:21-52

**Comment by msimonc** [comment]
Solution: 
npm install json-loader including the following into you webpack config:
			{
				test: /\.json$/,
				loader: "json-loader"
			},
